// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNoQABWztBXhBbOi72yv3YXAfvt4BlaY',
    appId: '1:385136272390:web:448244c8f26af659620f87',
    messagingSenderId: '385136272390',
    projectId: 'webmsgcom',
    authDomain: 'webmsgcom.firebaseapp.com',
    storageBucket: 'webmsgcom.firebasestorage.app',
    measurementId: 'G-ZF8ZFTK7Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9YHbXaqgYKEhcnvYHxaivH2plX8oWjEk',
    appId: '1:385136272390:android:920fd7a7549b1a41620f87',
    messagingSenderId: '385136272390',
    projectId: 'webmsgcom',
    storageBucket: 'webmsgcom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfr7JP2e4H0aexoWLPzb0zib1SoEqB98',
    appId: '1:385136272390:ios:81ef456c49ba9af8620f87',
    messagingSenderId: '385136272390',
    projectId: 'webmsgcom',
    storageBucket: 'webmsgcom.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByfr7JP2e4H0aexoWLPzb0zib1SoEqB98',
    appId: '1:385136272390:ios:81ef456c49ba9af8620f87',
    messagingSenderId: '385136272390',
    projectId: 'webmsgcom',
    storageBucket: 'webmsgcom.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFNoQABWztBXhBbOi72yv3YXAfvt4BlaY',
    appId: '1:385136272390:web:d5e89a49fdb53297620f87',
    messagingSenderId: '385136272390',
    projectId: 'webmsgcom',
    authDomain: 'webmsgcom.firebaseapp.com',
    storageBucket: 'webmsgcom.firebasestorage.app',
    measurementId: 'G-T9JDV0CSR8',
  );
}
